// Copyright (c) Microsoft Corporation
// The Microsoft Corporation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

// Copyright (c) Microsoft Corporation
// The Microsoft Corporation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

// This file exists for backwards compatibility with existing code.
// The actual interface is generated by CsWin32 from NativeMethods.txt
using Windows.Win32.UI.Shell;

namespace Microsoft.CmdPal.Ext.WindowsTerminal.Helpers
{
    // Alias to the CsWin32 generated interface
    using IApplicationActivationManager = Windows.Win32.UI.Shell.IApplicationActivationManager;
}
